# Generated by Django 4.0.3 on 2022-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=1)),
                ('sexo', models.CharField(max_length=10)),
                ('referencia', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('editado', models.DateTimeField()),
            ],
        ),
    ]
