# Generated by Django 4.0.3 on 2022-03-23 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='cantidadContada',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidadSistema',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
