# Generated by Django 4.0.3 on 2022-03-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_rename_cantidad_producto_cantidadcontada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
    ]
