# Generated by Django 4.0.3 on 2022-03-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '__first__'),
        ('producto', '0007_rename_cantidadcontada_producto_enbloque2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.inventarios'),
            preserve_default=False,
        ),
    ]
