# Generated by Django 4.0.3 on 2022-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_rename_cantidadcontada_producto_enbloque2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='diferencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
